version: '3.7'
services: 
  dev:
    build:
      context: .
      dockerfile: ./.docker/dev/dockerfile
    tty: true
    stdin_open: true
    volumes: 
      - .:/code
      - ./.docker/dev/.pip/pip.conf:/root/.pip/pip.conf
      - python:/python
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: postgres:12
    environment: 
      POSTGRES_USER: 'postgres_user_dev'
      POSTGRES_PASSWORD: 'postgres_password_dev'
      POSTGRES_DB: 'rhythm-ninja-database'

volumes: 
  python:
